# --- SERVICE inference-api (NodePort para acceso externo) ---
apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: inference-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800

---
# --- DEPLOYMENT inference-api ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-api
  template:
    metadata:
      labels:
        app: inference-api
    spec:
      containers:
        - name: inference-api
          image: mariamon/inference-api:latest  # Reemplazado automáticamente por GitHub Actions
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio-nodeport:9000
            - name: MODEL_NAME
              value: BestHousePriceModel
            - name: AIRFLOW_CONN_POSTGRES_DEFAULT
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

