# SERVICE Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30990

---
# --- grafana.yaml ---

# DEPLOYMENT Grafana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000

---
# SERVICE Grafana
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30930
