name: Build, Push MLflow & Update Manifest

on:
  push:
    paths:
      - 'mlflow/**'
      - '.github/workflows/build-mlflow.yml'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t mariamon/mlflow:${{ env.IMAGE_TAG }} ./mlflow
          docker push mariamon/mlflow:${{ env.IMAGE_TAG }}

      - name: Update manifest image tag
        run: |
          sed -i "s|image: mariamon/mlflow:.*|image: mariamon/mlflow:${{ env.IMAGE_TAG }}|g" manifests/mlflow.yaml

      - name: Commit and Push updated manifest
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_PUSH }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add manifests/*.yaml

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git commit -am "Update MLflow image tag to ${{ env.IMAGE_TAG }}"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/Maria-mon/MLOPS_Proyecto_Final.git
            git push origin main
          fi

