name: Build, Push API & Update Manifest

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/build-api.yml'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t mariamon/inference-api:${{ env.IMAGE_TAG }} ./api
          docker push mariamon/inference-api:${{ env.IMAGE_TAG }}

      - name: Update manifest image tag
        run: |
          sed -i "s|image: mariamon/inference-api:.*|image: mariamon/inference-api:${{ env.IMAGE_TAG }}|g" manifests/api.yaml

      - name: Commit and Push updated manifest
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update API image tag to ${{ env.IMAGE_TAG }}"
          git push

